### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by nomansky2** [amir22hr/robot_move#1]
@amir22hr was not working database for me .

Please fix it.

> you should node update``

**Comment by amir22hr** [comment]
> @amir22hr was not working database for me .
> 
> Please fix it.
> 
>~~ > you should node update``~~

**Comment by nomansky2** [comment]
> > @amir22hr was not working database for me .
> > Please fix it.
> > ~~ > you should node update``~~

Jdudune

**Comment by amir22hr** [comment]
Hh
